services:
  - type: web
    name: universal-platform-backend
    runtime: node
    buildCommand: npm ci && npm run build && pwd && ls -la && ls -la dist
    startCommand: pwd && ls -la dist && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
